<?php
session_start();
if(!isset($_SESSION['user']) || !in_array($_SESSION['user']['role'],['admin','super_admin'])){
    header("Location: index.php"); exit();
}
require 'db.php';

// Fetch performance data
$res = mysqli_query($conn, "SELECT e.first_name, e.last_name, e.emp_id, e.designation,
    (SELECT COUNT(*) FROM tasks WHERE emp_id=e.emp_id) as total_tasks,
    (SELECT COUNT(*) FROM tasks WHERE emp_id=e.emp_id AND status='completed') as completed,
    (SELECT COUNT(*) FROM tasks WHERE emp_id=e.emp_id AND status='pending') as pending,
    (SELECT COUNT(*) FROM tasks WHERE emp_id=e.emp_id AND status='in_progress') as in_progress,
    (SELECT COUNT(*) FROM attendance WHERE emp_id=e.emp_id AND status='present') as present_days,
    (SELECT COUNT(*) FROM attendance WHERE emp_id=e.emp_id AND status='absent') as absent_days,
    (SELECT COUNT(*) FROM attendance WHERE emp_id=e.emp_id AND status='late') as late_days,
    (SELECT COUNT(*) FROM leaves WHERE emp_id=e.emp_id AND status='approved') as approved_leaves,
    (SELECT COUNT(*) FROM performance WHERE emp_id=e.emp_id) as skills
    FROM employees e
    ORDER BY e.first_name ASC");

$rows = [];
while($r = mysqli_fetch_assoc($res)){
    // Calculate performance score out of 100
    $task_score = $r['total_tasks'] > 0 ? round(($r['completed'] / $r['total_tasks']) * 40) : 0; // 40%
    $att_score  = ($r['present_days'] + $r['late_days']) > 0
        ? round(($r['present_days'] / ($r['present_days'] + $r['absent_days'] + 1)) * 40) : 0;   // 40%
    $skill_score = min($r['skills'] * 4, 20); // 20% — max 5 skills = 20pts
    $r['score']  = min($task_score + $att_score + $skill_score, 100);

    // Grade
    if($r['score'] >= 85)      $r['grade'] = 'A+ Excellent';
    elseif($r['score'] >= 70)  $r['grade'] = 'A Good';
    elseif($r['score'] >= 55)  $r['grade'] = 'B Average';
    elseif($r['score'] >= 40)  $r['grade'] = 'C Below Average';
    else                        $r['grade'] = 'D Needs Improvement';

    $rows[] = $r;
}

// Excel headers
$filename = "Performance_Report_".date('d_M_Y').".xls";
header("Content-Type: application/vnd.ms-excel");
header("Content-Disposition: attachment; filename=\"$filename\"");
header("Pragma: no-cache");
header("Expires: 0");
?>
<html>
<head>
<meta charset="UTF-8">
<style>
    body   { font-family: Calibri, Arial, sans-serif; font-size: 11pt; }
    .title { font-size: 16pt; font-weight: bold; color: #1a1a2e; }
    table  { border-collapse: collapse; width: 100%; table-layout: auto; }
    th     { background-color: #1a1a2e; color: white; padding: 10px 16px; text-align: center; border: 1px solid #bbb; white-space: nowrap; font-size: 11pt; }
    td     { padding: 8px 16px; border: 1px solid #ddd; text-align: center; white-space: nowrap; font-size: 11pt; min-width: 110px; }
    tr:nth-child(even) { background-color: #f9fafb; }
    .grade-a  { background-color: #dcfce7; color: #16a34a; font-weight: 700; }
    .grade-b  { background-color: #eff6ff; color: #2563eb; font-weight: 700; }
    .grade-c  { background-color: #fef3c7; color: #d97706; font-weight: 700; }
    .grade-d  { background-color: #fee2e2; color: #dc2626; font-weight: 700; }
    .summary  { background-color: #eff6ff; font-weight: bold; }
</style>
</head>
<body>

<p class="title">📊 Employee Performance Report — Aller Technologies</p>
<p style="font-size:12px;color:#6b7280;">
    Generated by: <strong><?php echo $_SESSION['user']['name']; ?></strong> &nbsp;|&nbsp;
    Total Employees: <strong><?php echo count($rows); ?></strong> &nbsp;|&nbsp;
    Generated: <strong><?php echo date('d M Y, h:i A'); ?></strong>
</p>

<!-- Scoring Guide -->
<table style="width:auto;margin-bottom:16px;">
    <tr>
        <th colspan="4" style="background:#1a1a2e;">📋 Scoring Criteria</th>
    </tr>
    <tr>
        <td><strong>Task Completion</strong><br>40 points</td>
        <td><strong>Attendance</strong><br>40 points</td>
        <td><strong>Skills</strong><br>20 points</td>
        <td><strong>Total</strong><br>100 points</td>
    </tr>
</table>

<!-- Detail Table -->
<table>
    <thead>
        <tr>
            <th>#</th>
            <th>Employee Name</th>
            <th>Emp ID</th>
            <th>Designation</th>
            <th>Total Tasks</th>
            <th>Completed</th>
            <th>Pending</th>
            <th>In Progress</th>
            <th>Present Days</th>
            <th>Absent Days</th>
            <th>Late Days</th>
            <th>Approved Leaves</th>
            <th>Skills</th>
            <th>Score /100</th>
            <th>Grade</th>
        </tr>
    </thead>
    <tbody>
    <?php
    if(empty($rows)){
        echo "<tr><td colspan='15' style='text-align:center;color:#9ca3af;'>No performance data found.</td></tr>";
    }
    $sr = 1;
    foreach($rows as $row){
        // Grade color
        $grade_class = 'grade-d';
        if(strpos($row['grade'],'A+')!==false || strpos($row['grade'],'A G')!==false) $grade_class='grade-a';
        elseif(strpos($row['grade'],'B')!==false) $grade_class='grade-b';
        elseif(strpos($row['grade'],'C')!==false) $grade_class='grade-c';

        echo "<tr>
            <td>{$sr}</td>
            <td><strong>{$row['first_name']} {$row['last_name']}</strong></td>
            <td>{$row['emp_id']}</td>
            <td>{$row['designation']}</td>
            <td>{$row['total_tasks']}</td>
            <td style='color:#16a34a;font-weight:600;'>{$row['completed']}</td>
            <td style='color:#dc2626;font-weight:600;'>{$row['pending']}</td>
            <td style='color:#d97706;font-weight:600;'>{$row['in_progress']}</td>
            <td style='color:#16a34a;'>{$row['present_days']}</td>
            <td style='color:#dc2626;'>{$row['absent_days']}</td>
            <td style='color:#d97706;'>{$row['late_days']}</td>
            <td>{$row['approved_leaves']}</td>
            <td>{$row['skills']}</td>
            <td><strong>{$row['score']}</strong></td>
            <td class='{$grade_class}'>{$row['grade']}</td>
        </tr>";
        $sr++;
    }
    ?>
    </tbody>
</table>

<br>
<p style="font-size:11px;color:#9ca3af;">
    * A+ (85-100) | A (70-84) | B (55-69) | C (40-54) | D (0-39) &nbsp;|&nbsp;
    * Confidential — For Internal Use Only &nbsp;|&nbsp;
    * Generated by EMS — Aller Technologies
</p>

</body>
</html>
<?php mysqli_close($conn); ?>
