<?php
session_start();
if(!isset($_SESSION['user']) || $_SESSION['user']['role']!='employee'){
    header("Location: index.php"); exit();
}
require 'db.php';

$user_id    = $_SESSION['user']['id'];
$emp_result = mysqli_query($conn, "SELECT * FROM employees WHERE user_id='$user_id'");
$emp        = mysqli_fetch_assoc($emp_result);
$emp_id     = $emp['emp_id'];
$emp_name   = $emp['first_name'].' '.$emp['last_name'];

// Get selected month (default = current month)
// SECURITY: ts_month must match YYYY-MM before it's used in SQL — it was
// going straight into the query unvalidated.
$ts_month = isset($_GET['ts_month']) ? $_GET['ts_month'] : date('Y-m');
if(!preg_match('/^\d{4}-\d{2}$/', $ts_month)) $ts_month = date('Y-m');
$ts_year  = substr($ts_month, 0, 4);
$ts_mon   = substr($ts_month, 5, 2);
$month_label = date('F Y', strtotime($ts_month.'-01'));

// Fetch attendance data
$res = mysqli_query($conn, "SELECT * FROM attendance WHERE emp_id='$emp_id' AND YEAR(date)='$ts_year' AND MONTH(date)='$ts_mon' ORDER BY date ASC");

$rows      = [];
$total_hrs = 0;
$total_ot  = 0;

while($r = mysqli_fetch_assoc($res)){
    $hrs = 0;
    if($r['check_in'] && $r['check_out']){
        $in  = strtotime($r['check_in']);
        $out = strtotime($r['check_out']);
        if($out > $in) $hrs = ($out - $in) / 3600;
    }
    $ot = max(0, $hrs - 8);
    $r['hours']    = $hrs;
    $r['overtime'] = $ot;
    $total_hrs    += $hrs;
    $total_ot     += $ot;
    $rows[]        = $r;
}

// ===== EXCEL EXPORT HEADERS =====
$filename = "Timesheet_{$emp_name}_{$month_label}.xls";
$filename = str_replace(' ', '_', $filename);

header("Content-Type: application/vnd.ms-excel");
header("Content-Disposition: attachment; filename=\"$filename\"");
header("Pragma: no-cache");
header("Expires: 0");
?>
<html>
<head>
<meta charset="UTF-8">
<style>
    body { font-family: Calibri, Arial, sans-serif; font-size: 11pt; }
    .title { font-size: 16pt; font-weight: bold; color: #1a1a2e; }
    .subtitle { font-size: 12px; color: #6b7280; margin-bottom: 10px; }
    table { border-collapse: collapse; width: 100%; table-layout: auto; }
    th { background-color: #1a1a2e; color: white; padding: 10px 16px; text-align: center; border: 1px solid #bbb; white-space: nowrap; font-size: 11pt; }
    td { padding: 8px 16px; border: 1px solid #ddd; text-align: center; white-space: nowrap; font-size: 11pt; min-width: 110px; }
    tr:nth-child(even) { background-color: #f9fafb; }
    .present  { background-color: #dcfce7; color: #16a34a; font-weight: 600; }
    .absent   { background-color: #fee2e2; color: #dc2626; font-weight: 600; }
    .late     { background-color: #fef3c7; color: #d97706; font-weight: 600; }
    .summary  { background-color: #eff6ff; font-weight: bold; }
    .ot-cell  { color: #16a34a; font-weight: 600; }
</style>
</head>
<body>

<p class="title">📋 Employee Timesheet — <?php echo $month_label; ?></p>
<p class="subtitle">
    Employee: <strong><?php echo $emp_name; ?></strong> &nbsp;|&nbsp;
    Employee ID: <strong><?php echo $emp_id; ?></strong> &nbsp;|&nbsp;
    Generated: <strong><?php echo date('d M Y, h:i A'); ?></strong>
</p>

<table>
    <thead>
        <tr>
            <th>#</th>
            <th>Date</th>
            <th>Day</th>
            <th>Check In</th>
            <th>Check Out</th>
            <th>Hours Worked</th>
            <th>Overtime</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
    <?php
    if(empty($rows)){
        echo "<tr><td colspan='8' style='text-align:center;color:#9ca3af;'>No records found for $month_label</td></tr>";
    }
    $sr = 1;
    foreach($rows as $row){
        $day      = date('D', strtotime($row['date']));
        $hrs_disp = $row['hours'] > 0 ? number_format($row['hours'],1).' hrs' : '-';
        $ot_disp  = $row['overtime'] > 0 ? '+'.number_format($row['overtime'],1).' hrs' : '-';
        $status   = ucfirst(str_replace('_',' ', $row['status']));
        $status_class = strtolower($row['status']);

        echo "<tr>
            <td>{$sr}</td>
            <td>{$row['date']}</td>
            <td>{$day}</td>
            <td>".($row['check_in'] ?: '-')."</td>
            <td>".($row['check_out'] ?: '-')."</td>
            <td>{$hrs_disp}</td>
            <td class='ot-cell'>{$ot_disp}</td>
            <td class='{$status_class}'>{$status}</td>
        </tr>";
        $sr++;
    }
    ?>
    <!-- Summary Row -->
    <tr class="summary">
        <td colspan="5" style="text-align:right;"><strong>Monthly Total:</strong></td>
        <td><strong><?php echo number_format($total_hrs,1); ?> hrs</strong></td>
        <td><strong><?php echo $total_ot > 0 ? '+'.number_format($total_ot,1).' hrs' : '-'; ?></strong></td>
        <td><strong><?php echo count($rows); ?> days</strong></td>
    </tr>
    </tbody>
</table>

<br>
<p style="font-size:11px;color:#9ca3af;">
    * Standard working hours: 8 hrs/day &nbsp;|&nbsp;
    * Overtime = Hours worked beyond 8 hrs &nbsp;|&nbsp;
    * Generated by EMS — Aller Technologies
</p>

</body>
</html>
<?php
mysqli_close($conn);
?>
