<?php
session_start();
if(!isset($_SESSION['user']) || !in_array($_SESSION['user']['role'],['admin','super_admin'])){
    header("Location: index.php"); exit();
}
require 'db.php';

// Fetch all employees with department name
$res = mysqli_query($conn, "SELECT u.id, u.name, u.email, u.role,
    e.emp_id, e.designation, e.contact, e.blood_group, e.dob, e.address,
    d.dept_name
    FROM users u
    LEFT JOIN employees e ON u.id = e.user_id
    LEFT JOIN departments d ON e.dept_id = d.dept_id
    WHERE u.role = 'employee'
    ORDER BY u.name ASC");

$rows = [];
while($r = mysqli_fetch_assoc($res)){
    $rows[] = $r;
}

// Excel headers
$filename = "Employee_List_".date('d_M_Y').".xls";
header("Content-Type: application/vnd.ms-excel");
header("Content-Disposition: attachment; filename=\"$filename\"");
header("Pragma: no-cache");
header("Expires: 0");
?>
<html>
<head>
<meta charset="UTF-8">
<style>
    body   { font-family: Calibri, Arial, sans-serif; font-size: 11pt; }
    .title { font-size: 16pt; font-weight: bold; color: #1a1a2e; }
    table  { border-collapse: collapse; width: 100%; table-layout: auto; }
    th     { background-color: #1a1a2e; color: white; padding: 10px 16px; text-align: center; border: 1px solid #bbb; white-space: nowrap; font-size: 11pt; }
    td     { padding: 8px 16px; border: 1px solid #ddd; text-align: center; white-space: nowrap; font-size: 11pt; min-width: 110px; }
    tr:nth-child(even) { background-color: #f9fafb; }
    .summary { background-color: #eff6ff; font-weight: bold; }
</style>
</head>
<body>

<p class="title">👥 Employee Master List — Aller Technologies</p>
<p style="font-size:12px;color:#6b7280;">
    Generated by: <strong><?php echo $_SESSION['user']['name']; ?></strong> &nbsp;|&nbsp;
    Total Employees: <strong><?php echo count($rows); ?></strong> &nbsp;|&nbsp;
    Generated: <strong><?php echo date('d M Y, h:i A'); ?></strong>
</p>

<table>
    <thead>
        <tr>
            <th>#</th>
            <th>Employee ID</th>
            <th>Full Name</th>
            <th>Email</th>
            <th>Contact</th>
            <th>Designation</th>
            <th>Department</th>
            <th>Blood Group</th>
            <th>Date of Birth</th>
            <th>Address</th>
        </tr>
    </thead>
    <tbody>
    <?php
    if(empty($rows)){
        echo "<tr><td colspan='10' style='text-align:center;color:#9ca3af;'>No employees found.</td></tr>";
    }
    $sr = 1;
    foreach($rows as $row){
        echo "<tr>
            <td>{$sr}</td>
            <td>{$row['emp_id']}</td>
            <td>{$row['name']}</td>
            <td>{$row['email']}</td>
            <td>{$row['contact']}</td>
            <td>{$row['designation']}</td>
            <td>".($row['dept_name'] ?: '-')."</td>
            <td>".($row['blood_group'] ?: '-')."</td>
            <td>".($row['dob'] ?: '-')."</td>
            <td>".($row['address'] ?: '-')."</td>
        </tr>";
        $sr++;
    }
    ?>
    <tr class="summary">
        <td colspan="10" style="text-align:right;">
            <strong>Total Employees: <?php echo count($rows); ?></strong>
        </td>
    </tr>
    </tbody>
</table>

<br>
<p style="font-size:11px;color:#9ca3af;">
    * Confidential — For Internal Use Only &nbsp;|&nbsp;
    * Generated by EMS — Aller Technologies
</p>

</body>
</html>
<?php mysqli_close($conn); ?>
