<?php
session_start();
if(!isset($_SESSION['user']) || !in_array($_SESSION['user']['role'],['admin','super_admin'])){
    header("Location: index.php"); exit();
}
require 'db.php';

// Month/Year filter
// SECURITY: month must be a real month name, year must be an integer —
// both previously went straight into SQL unvalidated.
$valid_months = ['January','February','March','April','May','June','July','August','September','October','November','December'];
$sel_month = in_array($_GET['month'] ?? '', $valid_months, true) ? $_GET['month'] : date('F');
$sel_year  = (int) ($_GET['year'] ?? date('Y'));

// Fetch salary records
$res = mysqli_query($conn, "SELECT s.*, e.first_name, e.last_name, e.emp_id, e.designation
    FROM salary s
    JOIN employees e ON s.emp_id = e.emp_id
    WHERE s.month='$sel_month' AND s.year='$sel_year'
    ORDER BY e.first_name ASC");

$rows        = [];
$total_basic = 0;
$total_allow = 0;
$total_ded   = 0;
$total_lop   = 0;
$total_net   = 0;

while($r = mysqli_fetch_assoc($res)){
    $total_basic += $r['basic_pay'];
    $total_allow += $r['allowances'];
    $total_ded   += $r['deductions'];
    $total_lop   += isset($r['lop_amount']) ? $r['lop_amount'] : 0;
    $total_net   += $r['net_pay'];
    $rows[]       = $r;
}

// Excel headers
$filename = "Salary_Report_{$sel_month}_{$sel_year}.xls";
header("Content-Type: application/vnd.ms-excel");
header("Content-Disposition: attachment; filename=\"$filename\"");
header("Pragma: no-cache");
header("Expires: 0");
?>
<html>
<head>
<meta charset="UTF-8">
<style>
    body   { font-family: Calibri, Arial, sans-serif; font-size: 11pt; }
    .title { font-size: 16pt; font-weight: bold; color: #1a1a2e; }
    table  { border-collapse: collapse; width: 100%; table-layout: auto; }
    th     { background-color: #1a1a2e; color: white; padding: 10px 16px; text-align: center; border: 1px solid #bbb; white-space: nowrap; font-size: 11pt; }
    td     { padding: 8px 16px; border: 1px solid #ddd; text-align: center; white-space: nowrap; font-size: 11pt; min-width: 110px; }
    tr:nth-child(even) { background-color: #f9fafb; }
    .net   { background-color: #dcfce7; color: #16a34a; font-weight: 700; }
    .ded   { background-color: #fee2e2; color: #dc2626; }
    .lop   { background-color: #fef3c7; color: #d97706; }
    .summary { background-color: #1a1a2e; color: white; font-weight: bold; }
</style>
</head>
<body>

<p class="title">💰 Company Salary Report — <?php echo $sel_month.' '.$sel_year; ?></p>
<p style="font-size:12px;color:#6b7280;">
    Generated by: <strong><?php echo $_SESSION['user']['name']; ?></strong> &nbsp;|&nbsp;
    Generated: <strong><?php echo date('d M Y, h:i A'); ?></strong> &nbsp;|&nbsp;
    Total Employees: <strong><?php echo count($rows); ?></strong>
</p>

<!-- Summary -->
<table style="width:auto;margin-bottom:16px;">
    <tr>
        <th>Total Basic Pay</th>
        <th>Total Allowances</th>
        <th>Total Deductions</th>
        <th>Total LOP</th>
        <th style="background:#16a34a;">Total Net Pay</th>
    </tr>
    <tr>
        <td>₹<?php echo number_format($total_basic,2); ?></td>
        <td>₹<?php echo number_format($total_allow,2); ?></td>
        <td class="ded">₹<?php echo number_format($total_ded,2); ?></td>
        <td class="lop">₹<?php echo number_format($total_lop,2); ?></td>
        <td class="net">₹<?php echo number_format($total_net,2); ?></td>
    </tr>
</table>

<!-- Detail Table -->
<table>
    <thead>
        <tr>
            <th>#</th>
            <th>Employee Name</th>
            <th>Employee ID</th>
            <th>Designation</th>
            <th>Basic Pay (₹)</th>
            <th>Allowances (₹)</th>
            <th>Deductions/PF (₹)</th>
            <th>LOP Days</th>
            <th>LOP Amount (₹)</th>
            <th>Net Pay (₹)</th>
            <th>Month</th>
            <th>Year</th>
        </tr>
    </thead>
    <tbody>
    <?php
    if(empty($rows)){
        echo "<tr><td colspan='12' style='text-align:center;color:#9ca3af;'>No salary records found for $sel_month $sel_year.</td></tr>";
    }
    $sr = 1;
    foreach($rows as $row){
        $lop_days = isset($row['lop_days'])   ? $row['lop_days']   : 0;
        $lop_amt  = isset($row['lop_amount']) ? $row['lop_amount'] : 0;
        echo "<tr>
            <td>{$sr}</td>
            <td>{$row['first_name']} {$row['last_name']}</td>
            <td>{$row['emp_id']}</td>
            <td>{$row['designation']}</td>
            <td>₹".number_format($row['basic_pay'],2)."</td>
            <td>₹".number_format($row['allowances'],2)."</td>
            <td class='ded'>₹".number_format($row['deductions'],2)."</td>
            <td class='lop'>{$lop_days} days</td>
            <td class='lop'>₹".number_format($lop_amt,2)."</td>
            <td class='net'>₹".number_format($row['net_pay'],2)."</td>
            <td>{$row['month']}</td>
            <td>{$row['year']}</td>
        </tr>";
        $sr++;
    }
    ?>
    <!-- Total Row -->
    <tr class="summary">
        <td colspan="4" style="text-align:right;">Grand Total:</td>
        <td>₹<?php echo number_format($total_basic,2); ?></td>
        <td>₹<?php echo number_format($total_allow,2); ?></td>
        <td>₹<?php echo number_format($total_ded,2); ?></td>
        <td colspan="2">₹<?php echo number_format($total_lop,2); ?></td>
        <td>₹<?php echo number_format($total_net,2); ?></td>
        <td colspan="2"></td>
    </tr>
    </tbody>
</table>

<br>
<p style="font-size:11px;color:#9ca3af;">
    * Net Pay = Basic Pay + Allowances - Deductions - LOP Amount &nbsp;|&nbsp;
    * Generated by EMS — Aller Technologies
</p>

</body>
</html>
<?php mysqli_close($conn); ?>
