<?php
session_start();
if(!isset($_SESSION['user']) || !in_array($_SESSION['user']['role'],['admin','super_admin'])){
    header("Location: index.php"); exit();
}
require 'db.php';

// Month filter
// SECURITY: ts_month must match YYYY-MM before it's used in SQL — it was
// going straight into the query unvalidated.
$ts_month = isset($_GET['ts_month']) ? $_GET['ts_month'] : date('Y-m');
if(!preg_match('/^\d{4}-\d{2}$/', $ts_month)) $ts_month = date('Y-m');
$ts_year  = substr($ts_month, 0, 4);
$ts_mon   = substr($ts_month, 5, 2);
$month_label = date('F Y', strtotime($ts_month.'-01'));

// Fetch all employees attendance for selected month
$res = mysqli_query($conn, "SELECT e.first_name, e.last_name, e.emp_id, e.designation,
    a.date, a.check_in, a.check_out, a.status
    FROM attendance a
    JOIN employees e ON a.emp_id = e.emp_id
    WHERE YEAR(a.date)='$ts_year' AND MONTH(a.date)='$ts_mon'
    ORDER BY e.first_name ASC, a.date ASC");

$rows         = [];
$total_present = 0;
$total_absent  = 0;
$total_late    = 0;
$total_wfh     = 0;

while($r = mysqli_fetch_assoc($res)){
    $hrs = 0;
    if($r['check_in'] && $r['check_out']){
        $in  = strtotime($r['check_in']);
        $out = strtotime($r['check_out']);
        if($out > $in) $hrs = ($out - $in) / 3600;
    }
    $r['hours'] = $hrs;
    if($r['status'] == 'present')        $total_present++;
    if($r['status'] == 'absent')         $total_absent++;
    if($r['status'] == 'late')           $total_late++;
    if($r['status'] == 'work_from_home') $total_wfh++;
    $rows[] = $r;
}

// Excel headers
$filename = "Attendance_Report_{$month_label}.xls";
$filename = str_replace(' ', '_', $filename);

header("Content-Type: application/vnd.ms-excel");
header("Content-Disposition: attachment; filename=\"$filename\"");
header("Pragma: no-cache");
header("Expires: 0");
?>
<html>
<head>
<meta charset="UTF-8">
<style>
    body  { font-family: Calibri, Arial, sans-serif; font-size: 11pt; }
    .title { font-size: 16pt; font-weight: bold; color: #1a1a2e; }
    table { border-collapse: collapse; width: 100%; table-layout: auto; }
    th    { background-color: #1a1a2e; color: white; padding: 10px 16px; text-align: center; border: 1px solid #bbb; white-space: nowrap; font-size: 11pt; }
    td    { padding: 8px 16px; border: 1px solid #ddd; text-align: center; white-space: nowrap; font-size: 11pt; min-width: 110px; }
    tr:nth-child(even) { background-color: #f9fafb; }
    .present        { background-color: #dcfce7; color: #16a34a; font-weight: 600; }
    .absent         { background-color: #fee2e2; color: #dc2626; font-weight: 600; }
    .late           { background-color: #fef3c7; color: #d97706; font-weight: 600; }
    .work_from_home { background-color: #eff6ff; color: #2563eb; font-weight: 600; }
    .half_day       { background-color: #fdf4ff; color: #7c3aed; font-weight: 600; }
    .summary        { background-color: #eff6ff; font-weight: bold; }
</style>
</head>
<body>

<p class="title">📋 Company Attendance Report — <?php echo $month_label; ?></p>
<p style="font-size:12px;color:#6b7280;">
    Generated by: <strong><?php echo $_SESSION['user']['name']; ?></strong> &nbsp;|&nbsp;
    Role: <strong><?php echo ucfirst($_SESSION['user']['role']); ?></strong> &nbsp;|&nbsp;
    Generated: <strong><?php echo date('d M Y, h:i A'); ?></strong>
</p>

<!-- Summary -->
<table style="width:auto;margin-bottom:16px;">
    <tr>
        <th style="background:#16a34a;">Present</th>
        <th style="background:#dc2626;">Absent</th>
        <th style="background:#d97706;">Late</th>
        <th style="background:#2563eb;">Work From Home</th>
        <th style="background:#1a1a2e;">Total Records</th>
    </tr>
    <tr>
        <td class="present"><?php echo $total_present; ?></td>
        <td class="absent"><?php echo $total_absent; ?></td>
        <td class="late"><?php echo $total_late; ?></td>
        <td class="work_from_home"><?php echo $total_wfh; ?></td>
        <td><strong><?php echo count($rows); ?></strong></td>
    </tr>
</table>

<!-- Detail Table -->
<table>
    <thead>
        <tr>
            <th>#</th>
            <th>Employee Name</th>
            <th>Employee ID</th>
            <th>Designation</th>
            <th>Date</th>
            <th>Day</th>
            <th>Check In</th>
            <th>Check Out</th>
            <th>Hours Worked</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
    <?php
    if(empty($rows)){
        echo "<tr><td colspan='10' style='text-align:center;color:#9ca3af;'>No records found for $month_label</td></tr>";
    }
    $sr = 1;
    foreach($rows as $row){
        $day      = date('D', strtotime($row['date']));
        $hrs_disp = $row['hours'] > 0 ? number_format($row['hours'],1).' hrs' : '-';
        $status   = ucfirst(str_replace('_',' ', $row['status']));
        echo "<tr>
            <td>{$sr}</td>
            <td>{$row['first_name']} {$row['last_name']}</td>
            <td>{$row['emp_id']}</td>
            <td>{$row['designation']}</td>
            <td>{$row['date']}</td>
            <td>{$day}</td>
            <td>".($row['check_in'] ?: '-')."</td>
            <td>".($row['check_out'] ?: '-')."</td>
            <td>{$hrs_disp}</td>
            <td class='{$row['status']}'>{$status}</td>
        </tr>";
        $sr++;
    }
    ?>
    <tr class="summary">
        <td colspan="9" style="text-align:right;"><strong>Total Records:</strong></td>
        <td><strong><?php echo count($rows); ?></strong></td>
    </tr>
    </tbody>
</table>

<br>
<p style="font-size:11px;color:#9ca3af;">
    * Generated by EMS — Aller Technologies &nbsp;|&nbsp;
    * Standard check-in time: 09:00 AM
</p>

</body>
</html>
<?php mysqli_close($conn); ?>
